# use tmuxinator
# prefix + q 

set-option -g prefix C-a
bind-key C-a send-prefix
unbind-key C-b

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind | split-window -h
bind - split-window -v

set-option -g base-index 1
set-option -g mouse on

set-option -g status-right '#(tmux show-options -g prefix)'

set -g window-style 'fg=colour22,bg=colour234'
set -g window-active-style 'fg=colour46,bg=colour0'
